# Generated by Django 5.2.4 on 2025-08-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('Compra a proveedor', 'Compra a proveedor'), ('Novedad (daño, pérdida)', 'Novedad (daño, pérdida)'), ('Venta', 'Venta'), ('Devolución', 'Devolución')], max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del movimiento', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
