# Generated by Django 5.2.4 on 2025-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio (COP)'),
        ),
    ]
